DATA PREPROCESSING

In [231]:
#importing  python packages 
  # for the data manuppulation
import pandas as pd
from sklearn.model_selection import train_test_split # to split the data in traning and testing
from sklearn.preprocessing import StandardScaler,LabelEncoder #
import pickle # saving the model in .pickel file



In [232]:
#load the data 
data=pd.read_csv('./Data/Churn_Modelling.csv')
#print the first few records
print(data.head())


   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         790

In [233]:
#preprocess the data
#drop the irrelavent data
#irrelavent data is [RowNumber , CustomerId ,  Surname]

data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [234]:
# check if column  got removed or not 
print(data.head())

   CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0  


In [235]:
#encode categorical variable 
# now we can see in our dataser gender is categirical variable

label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
#converted all the gender data into 0s and 1s
data



CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [236]:
#in geography colum also have more than 2 features
#i have to encode this same to convert in to 0s and 1s
#use onehot encoding 

from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [237]:
#hwo to print features for 
geo_encoder.toarray()


array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [238]:
geo_encoded_df=geo_onehot_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [239]:
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [240]:
##combine onehot encoder colums with the orignal data
#concaatination 
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()


CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

In [241]:
#save the encoder and scalaer 

with open('label_encoder_gender','wb') as file:
    pickle.dump(label_encoder_gen,file)
with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [242]:
#split the data set in to indipendent and dipendent data set
from matplotlib import testing


X=data.drop( 'Exited', axis=1)#dependent 
y=data['Exited']#indipendent data

# splitdata in to reaning and testing 

X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=42)

#scale all the features
scaler=StandardScaler()

X_train=scaler.fit_transform(x_train)
X_test=scaler.transform(X_test)


In [243]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [244]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)
    

ANN IMPLEMENTION 

In [245]:
import tensorflow as tf
from tensorflow.keras.models import Sequential # allows you to build a neural network layer-by-layer in a linear stack
from tensorflow.keras.layers import Dense #dense = node 
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime


In [246]:
x_train.shape[1]

12

In [247]:
#Bulding AAN model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ##HL 1 connected to input layer
    Dense(32,activation='relu'),## HL 2 dint need to define inpu_shape()
    Dense(1, activation='sigmoid')##output layer
    
])

c:\Users\Nikhil Warge\OneDrive\Documents\GitHub\Implementing-ANN-and-RNN-\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [248]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [249]:
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
loss=tf.keras.losses.BinaryCrossentropy()
loss

<LossFunctionWrapper(<function binary_crossentropy at 0x000001D342A71EE0>, kwargs={'from_logits': False, 'label_smoothing': 0.0, 'axis': -1})>

In [250]:
#compila the modle
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [251]:
#setup the tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit"+ datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [252]:
##setup early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [253]:
#Traing the model

history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7985 - loss: 0.4539 - val_accuracy: 0.8580 - val_loss: 0.3500
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8514 - loss: 0.3568 - val_accuracy: 0.8655 - val_loss: 0.3454
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8575 - loss: 0.3449 - val_accuracy: 0.8605 - val_loss: 0.3389
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8710 - loss: 0.3296 - val_accuracy: 0.8640 - val_loss: 0.3510
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8617 - loss: 0.3418 - val_accuracy: 0.8570 - val_loss: 0.3403
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8574 - loss: 0.3348 - val_accuracy: 0.8640 - val_loss: 0.3389
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8623 - loss: 0.3335 - val_accuracy: 0.8550 - val_loss: 0.3576
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8652 - loss: 0.3379 - val_accu

In [254]:
model.save('model.h5')



In [255]:
#load tensorboard session

%reload_ext tensorboard

In [256]:
#%tensorboard --logdir logs/fit20250119-013158

# show to the tensorboard dashboard

In [257]:
# load the trained model,scalar , pickal,onhot encoder

#load the encoder and scalar

with open('onehot_encoder_geo.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)


with open('label_encoder_gender','rb') as file:
    label_encoder_gen=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

    

In [258]:
# #Example input
# #we can not feed the user input as it is to model
# #we have to perform some preprocessing  on user input

input_data={ 
'CreditScore': 600,
'Geography':'France',
'Gender':'Male',
'Age': 40,
'Tenure':3,
'Balance':60000,
'NumOfProducts':2,
'HasCrCard': 1,
'IsActiveMember':1,
'EstimatedSalary':50000
}

In [259]:
#going to use onehotencoding for the : Geography

geo_encoded=label_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=label_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df


c:\Users\Nikhil Warge\OneDrive\Documents\GitHub\Implementing-ANN-and-RNN-\venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [260]:
input_df=pd.DataFrame([input_data])
input_df


CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [261]:
#encoded the gender
# data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
input_df['Gender']=label_encoder_gen.transform(input_df['Gender'])
input_df                                                   


CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France       1   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [262]:
#  combine onhot encoded with input data,
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       1   40       3    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [263]:
#scalling the input data

input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [264]:
#predict the churn or do predection
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step


array([[0.06143456]], dtype=float32)

In [266]:
predection_prob=prediction[0][0]
predection_prob

np.float32(0.061434556)

In [267]:
if predection_prob >0.5:
    print('The customer is likely to churn')
else:
    print('The customer is not likely to churn')

The customer is not likely to churn


#scalling the 